ORG 1000H
	MSJ1 DB "INGRESE PRIMER NUMERO: " 
	FIN1 DB ? 
	MSJ2 DB "INGRESE SEGUNDO NUMERO: " 
	FIN2 DB ? 
	NUM1 DB ? 
	NUM2 DB ?
	NUM3 DW ? 
ORG 2000H
	MOV BX, OFFSET MSJ1
	MOV AL, OFFSET FIN1 - OFFSET MSJ1
	INT 7
	MOV BX, OFFSET NUM1
	INT 6
	MOV BX, OFFSET MSJ2
	MOV AL, OFFSET FIN2 - OFFSET MSJ2
	INT 7
	MOV BX, OFFSET NUM2
	INT 6
	MOV DL, NUM1
	ADD DL, NUM2
  SUB DX, 30h
	MOV NUM3, DX
	MOV BX, OFFSET NUM3
	MOV AL, 1
	INT 7
	INT 0
END